"use client"
import Navbar from "@/components/Navbar";
import "animate.css"
import AnimatedItem from "@/components/AnimatedItem"
import Link from "next/link";
import { supabase } from './utils/supabase'
import { useEffect, useState } from "react";
import SellingItemH from "@/components/SellingItem_home";
export default function Home(){
  const [reviews, setReviews] = useState<any[]>([])
  async function getReviews() {
      const { data } = await supabase.from('reviews').select().eq('is_verified', true)
      if (data) {setReviews(data)}
    }
  
    useEffect(() => {
      getReviews()
    }, [])
    //stuff to get ACTUAL reviews made by users, i know overkill for this silly project
    return(
        <>
        <Navbar/>
        {/*this div has been generated by AI, since I had problems with centering myself using TailwindCSS
        (Only centering it on the screen, everything else was handmade) */}
        <div className="min-h-screen flex flex-col items-center justify-center text-center mt-3">
  <p className="max-w-4xl font-black text-4xl animate__animated animate__zoomInLeft">
    Best site to get your
    <em className="mx-3 font-inherit">perfectly priced</em>
    chairs
  </p>

  <p className="max-w-4xl font-black text-xl mt-4 animate__animated animate__zoomInLeft animate__delay-1s">
    and your
    <em className="mx-3 font-inherit">perfectly priced</em>
    singular table
  </p>
  <p className="mt-5 text-lg border border-dashed p-1" onClick={() => window.scroll({top: document.body.offsetHeight - 810,left: 0, behavior: 'smooth',})}>scroll down or click</p> {/*scroll down script from https://stackoverflow.com/questions/63031108/how-to-scroll-at-bottom-in-react-on-button */}
  <div className="grid-cols-2 md:grid"><SellingItemH text="Fancy office chair" price="340" desc="An comfortable, adjustable and fancy chair to keep you sitting and working comfortably"
        img="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%2Fid%2FOIP.USiAakfD7Sa6dc9GPxKTbQHaHa%3Fpid%3DApi&f=1&ipt=7b1bdb1ffb202c6e22d7d9b4fbbd45320e4aef5a943484a135752ef446a753b6&ipo=images"/>
        <SellingItemH text="Premium Gaming chair" price="320" desc="Gaming chair designed for gaming marathons"
        img="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.LhcbTgQTR9Y9-fLN8ChQGQHaHa%3Fpid%3DApi&f=1&ipt=da573b876c9117c6f0e096455ff70915ada87ac1d5dbe43ecfb3652a3a503239&ipo=images"/>
        </div>
  

</div>
{/*Got from a site, the template of quote boxes(review boxes in this case), did change it a bit though to center and to work good on mobile and on PC*/}
<p className="text-center md:mt-7 text-2xl">Just look at our <Link href="/reviews" className="border border-dashed pr-1 pl-1">reviews</Link> </p>
<div className="md:grid md:grid-flow-col md:grid-cols-3 items-center justify-center text-center gap-1 place-items-center md:mt-4">
{reviews.slice(-3).reverse().map((item) => (<AnimatedItem animation="animate__tada" className="mt-2 bg-neutral-primary-soft block md:min-w-63 md:max-w-lg p-6 border border-default rounded-base shadow-xs" key={item.email}>
  <p className="text-center mb-3 text-4xl font-semibold tracking-tight text-heading leading-8">{item.title}</p>
              <p className="text-xl italic">{item.content}</p>
              <p className="mb-3 text-2xl font-semibold tracking-tight text-heading leading-8">- {item.name}</p>
</AnimatedItem>))}
</div>
{!reviews.length && <div className="text-center"><p className="text-4xl font-semibold tracking-tight text-heading leading-8 mb-4">We have no reviews at the moment! you can write a review here:</p> <Link href="/reviews"><p className="text-4xl font-semibold text-heading leading-8 underline decoration-double">Reviews</p></Link></div>}

<p className="text-center text-xl mt-10">Now you know, go have a look:</p>
{/*Also got this thing from a site, a button template but change it up a bit to center it on the screen and to have some margings(and the text) */}
{/*https://uiverse.io/zymantas-katinas/little-puma-84 */}
<AnimatedItem animation="animate__shakeY" className="mt-6 mb-7 flex justify-self-center ">
<Link href={"/chairs"}
  className="relative group border-none bg-transparent p-0 outline-none cursor-pointer font-mono font-light uppercase text-base"
>
  <span
    className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-25 rounded-lg transform translate-y-0.5 transition duration-[600ms] ease-[cubic-bezier(0.3,0.7,0.4,1)] group-hover:translate-y-1 group-hover:duration-[250ms] group-active:translate-y-px"
  ></span>

  <span
    className="absolute top-0 left-0 w-full h-full rounded-lg bg-gradient-to-l from-[hsl(217,33%,16%)] via-[hsl(217,33%,32%)] to-[hsl(217,33%,16%)]"
  ></span>

  <span
    className="relative flex items-center justify-between py-3 px-6 text-lg text-white rounded-lg transform -translate-y-1 bg-gradient-to-r from-[#f27121] via-[#e94057] to-[#8a2387] gap-3 transition duration-[600ms] ease-[cubic-bezier(0.3,0.7,0.4,1)] group-hover:-translate-y-1.5 group-hover:duration-[250ms] group-active:-translate-y-0.5 brightness-100 group-hover:brightness-110"
  >
    <span className="select-none">Go to the Chair shop</span>

    <svg
      viewBox="0 0 20 20"
      fill="currentColor"
      className="w-5 h-5 ml-2 -mr-1 transition duration-250 group-hover:translate-x-1"
    >
      <path
        clipRule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        fillRule="evenodd"
      ></path>
    </svg>
  </span>
</Link>
</AnimatedItem>
<p id="copyrightxt" className="mb-5">©️ Aleksandr Ganzha</p>
        </>
    )
}