"use client"
import Navbar from "@/components/Navbar";
import "animate.css"
import AnimatedItem from "@/components/AnimatedItem"
import Link from "next/link";

export default function Home(){

    return(
        <>
        <Navbar/>
        {/*this div has been generated by AI, since I had problems with centering myself using TailwindCSS
        (Only centering it on the screen, everything else was handmade) */}
        <div className="min-h-screen flex flex-col items-center justify-center text-center -mt-30">
  <p className="max-w-4xl font-black text-4xl animate__animated animate__zoomInLeft">
    Best site to get your
    <em className="mx-3 font-inherit">perfectly priced</em>
    chairs
  </p>

  <p className="max-w-4xl font-black text-xl mt-4 animate__animated animate__zoomInLeft animate__delay-1s">
    and your
    <em className="mx-3 font-inherit">perfectly priced</em>
    singular table
  </p>
  <p className="mt-5 text-sm">scroll down pls</p>
</div>
{/*Got from a site, the template of quote boxes(review boxes in this case), did change it a bit though to center and to work good on mobile and on PC*/}
<p className="text-center md:mt-5 text-2xl">Just look at our reviews </p>
<div className="md:grid md:grid-flow-col md:grid-cols-3 items-center justify-center text-center gap-1 place-items-center md:mt-4">
<AnimatedItem animation="animate__tada" className="mt-2 bg-neutral-primary-soft block md:min-w-63 md:max-w-lg p-6 border border-default rounded-base shadow-xs">
  <h5 className="mb-3 text-4xl font-semibold tracking-tight text-heading leading-8">Jeffy E</h5>
    <p className="text-xl italic">I really liked the skeleton chair</p>
</AnimatedItem>
<AnimatedItem animation="animate__tada" className="mt-2 bg-neutral-primary-soft block md:max-w-lg p-6 border border-default rounded-base shadow-xs">
  <h5 className="mb-3 text-4xl font-semibold tracking-tight text-heading leading-8">ChatGPT</h5>
    <p className="text-xs">yes I actually asked ChatGPT to write me a review</p>
    <p className="text-lg italic">This chair site boldly asks important questions, like why a table costs $10,000, while casually selling skeleton chairs and emotional support seating dreams online paradise.
</p>
</AnimatedItem>
<AnimatedItem animation="animate__tada" className="mt-2 bg-neutral-primary-soft block md:max-w-lg p-6 border border-default rounded-base shadow-xs">
  <h5 className="mb-3 text-4xl font-semibold tracking-tight text-heading leading-8">Me (The one that made the site)</h5>
    <p className="text-xl italic">Kinda cool, the table is decently priced</p>
</AnimatedItem>
</div>

<p className="text-center text-xl mt-10">Now you know, go have a look:</p>
{/*Also got this thing from a site, a button template but change it up a bit to center it on the screen and to have some margings(and the text) */}
<AnimatedItem animation="animate__shakeY" className="mt-6 mb-7 flex justify-self-center ">
<Link href={"/chairs"}>
<button
  className="relative group border-none bg-transparent p-0 outline-none cursor-pointer font-mono font-light uppercase text-base"
>
  <span
    className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-25 rounded-lg transform translate-y-0.5 transition duration-[600ms] ease-[cubic-bezier(0.3,0.7,0.4,1)] group-hover:translate-y-1 group-hover:duration-[250ms] group-active:translate-y-px"
  ></span>

  <span
    className="absolute top-0 left-0 w-full h-full rounded-lg bg-gradient-to-l from-[hsl(217,33%,16%)] via-[hsl(217,33%,32%)] to-[hsl(217,33%,16%)]"
  ></span>

  <div
    className="relative flex items-center justify-between py-3 px-6 text-lg text-white rounded-lg transform -translate-y-1 bg-gradient-to-r from-[#f27121] via-[#e94057] to-[#8a2387] gap-3 transition duration-[600ms] ease-[cubic-bezier(0.3,0.7,0.4,1)] group-hover:-translate-y-1.5 group-hover:duration-[250ms] group-active:-translate-y-0.5 brightness-100 group-hover:brightness-110"
  >
    <span className="select-none">Go to the Chair shop</span>

    <svg
      viewBox="0 0 20 20"
      fill="currentColor"
      className="w-5 h-5 ml-2 -mr-1 transition duration-250 group-hover:translate-x-1"
    >
      <path
        clipRule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        fillRule="evenodd"
      ></path>
    </svg>
  </div>
</button>
</Link>
</AnimatedItem>
<p id="copyrightxt" className="mb-5">©️ Aleksandr Ganzha</p>
        </>
    )
}